### ISSUE TITLE
questions regarding defederation of crimew.gay

### ISSUE THREAD

**Issue by nyancrimew** [hachyderm/community#50]
This is not neccessarily an appeal, however i would like some clarification as to what "Violation" means in the context of a sudden instance suspension coming just minutes after i, as an admin, criticized certain policies of your instance. You are fully within your right to defederate from my instance, especially given i announced potential future defederation from you myself, however i feel like a clarification as to what actually lead to this moderation decision would help understanding your future interactions with other instances, as well as for what your users can except (since various users from your instance were following users on mine).

**Comment by krisnova** [comment]
Can anyone help me and provide more information on what exactly happened here? Is this the case of a blocked domain that should be unblocked or was there an incident that we need to be aware of? Sorry I am just really tight with time right now and trying to catch up.

If its an instance that is blocked that shouldn't be we can open it up. Just need to determine if that is the case or not.

**Comment by krisnova** [comment]
Hi Maia, 


So I just want to clarify a few things. I read **some** of [your posts](https://crimew.gay/maia) and as far as I know this is the first time myself or anyone on my server has looked at your page. 

So I just want to say that the messages about hachyderm have likely never been seen or reviewed by anyone on our end. Just want to make sure you understand that we don't have the bandwidth to follow you and keep up with your opinions about our servers. 

![image](https://user-images.githubusercontent.com/13757818/202548368-fda68bf2-59c6-4859-ba89-ecdfbdf03a36.png)

![image](https://user-images.githubusercontent.com/13757818/202548408-11727e24-c4e6-4f91-a38c-8540dfff3840.png)

![image](https://user-images.githubusercontent.com/13757818/202548639-6a82910b-3e33-489b-9d62-b074a5238211.png)

Regarding your inquiry about defederating with `crimew.gay` I couldn't find anything in our internal logs that show that you have done something wrong or that we have any reason to defederate with you. 

I went ahead and ensured that `hachyderm.io` is now completely open to federate with `crimew.gay`

--- 

A few other things. I read your posts about hachyderm and to be honest you have done more research and formed an opinion that exceeds most of our moderators. In other words you seem to have more to say about hachyderm than many of our mods. 

I would welcome you to our space to contribute your opinions, if you could do so respectfully. Not everyone on Hachyderm will agree with you, and our choice of words and their underlying meaning might be different than yours. 

For example we do have a no colonialism policy and it would appear that you feel strongly that we are not keeping up our end of the bargain somehow. It would be great if you we could find a way for you to share your thoughts with us without it turning into an argument or a fight. We value peace and collaboration above everything else. We must work together. 

Finally I will also start by saying that we are relatively new to the fediverse and will make mistakes. I noticed you mentioned a few domains that you believe we have blocked. Our current block list isn't entirely accurate and we have missed a few domains and blocked some by mistake. 

If you think there is anything in there that is a mistake please let us know and we are happy to review and make changes as needed.

To be candid, the liklihood that we have some vendetta against you or anyone else is very low. We are burnt out middle aged tech workers who are very tired and just trying to find a home. If we did anything by mistake we will just ask for forgiveness and fix the problem. We are too tired to have an opinion formed about your instance or any other instance that is anywhere nearly as mature as your opinion of ours. 

Thanks for hopefully giving us a chance to work together and collaborate

**Comment by krisnova** [comment]
For further transparency it looks like that your domain was automatically blocked because of some available issues. 

I want to be clear that the block had nothing to do with any human on our end forming an opinion about you or your content. The block was put in place automatically because our servers were unable to connect to your server to federate data to. 

![image](https://user-images.githubusercontent.com/13757818/202551625-a36e8e8c-0ec4-4d6e-8aec-9796c9b3111b.png)

**Comment by nyancrimew** [comment]
for the future it might make more sense to make the block reason be more transparent for automatic availability related blocks so this is easier to debug for instance administrators without requiring an issue to be opened here each time. thanks for the info

**Comment by krisnova** [comment]
We will see what we can do! We are very tired and are very new to this. 

It would appear that the rule in question is managed in this config file: https://github.com/mastodon/mastodon/blob/main/config/locales/en.yml#L453-L468

```yaml
    instances:
      availability:
        description_html:
          one: If delivering to the domain fails <strong>%{count} day</strong> without succeeding, no further delivery attempts will be made unless a delivery <em>from</em> the domain is received.
          other: If delivering to the domain fails on <strong>%{count} different days</strong> without succeeding, no further delivery attempts will be made unless a delivery <em>from</em> the domain is received.
        failure_threshold_reached: Failure threshold reached on %{date}.
        failures_recorded:
          one: Failed attempt on %{count} day.
          other: Failed attempts on %{count} different days.
        no_failures_recorded: No failures on record.
        title: Availability
        warning: The last attempt to connect to this server has been unsuccessful
      back_to_all: All
      back_to_limited: Limited
      back_to_warning: Warning
      by_domain: Domain
```

and I believe the `violation` language is just an automated label that the Mastodon open source project uses by default when this rule is violated. 

I will see if I can't find a better way to provide a list of the instances that are currently experiencing outages with federating against and offer those in a more cohesive place.

Is there anything else we can do to address any of your concerns? I noticed you had a lot to say about hachyderm on your page and I want to make sure we are doing all we can to understand any problems.
